import type { VenueCategory } from "@/types/database";

export interface SeedVenue {
  name: string;
  city: string;
  judet: string;
  address: string;
  description: string;
  category: VenueCategory;
  lat: number;
  lng: number;
}

export const seedVenues: SeedVenue[] = [
  // ── București ──────────────────────────────────────────────────────────────
  {
    name: "Caru' cu Bere",
    city: "București",
    judet: "Ilfov",
    address: "Str. Stavropoleos 5, Sector 3",
    description: "Berărie istorică din 1879, monument arhitectural în stil neogotic. Una dintre cele mai faimoase berării din Europa de Est, cu vitralii spectaculoase și bere la halbă din 1879.",
    category: "berarie",
    lat: 44.4346,
    lng: 26.1017,
  },
  {
    name: "Beerhouse",
    city: "București",
    judet: "Ilfov",
    address: "Calea Victoriei 91, Sector 1",
    description: "Cel mai mare bar de bere artizanală din centrul Bucureștiului, cu peste 100 de sortimente la robinet și la sticlă. Terasa de vară este legendară.",
    category: "berarie",
    lat: 44.4415,
    lng: 26.0964,
  },
  {
    name: "Hop Hooligans Taproom",
    city: "București",
    judet: "Ilfov",
    address: "Str. Logofăt Tăutu 55, Sector 3",
    description: "Berăria artizanală care a pus România pe harta craft beer-ului mondial. Sortimentele lor experimentale și colaborările internaționale sunt de neratat.",
    category: "berarie",
    lat: 44.4259,
    lng: 26.0894,
  },
  {
    name: "Berăria H",
    city: "București",
    judet: "Ilfov",
    address: "Str. Halelor 1, Sector 3",
    description: "Prima microberărie artizanală din București, fondată în 2012. Produce sortimente clasice și sezoniere cu malț românesc. Terasa din Hala Matache.",
    category: "berarie",
    lat: 44.4391,
    lng: 26.0886,
  },
  {
    name: "Narrative Brewing București",
    city: "București",
    judet: "Ilfov",
    address: "Str. Popa Nan 66, Sector 2",
    description: "Taproom modern cu beri narativ-tematice și design interior minimalist. Fiecare sortiment vine cu o poveste. IPA-urile lor sunt remarcabile.",
    category: "berarie",
    lat: 44.4401,
    lng: 26.1134,
  },
  {
    name: "Crama Oprișor",
    city: "București",
    judet: "Ilfov",
    address: "Str. Franceză 44, Sector 3",
    description: "Cramă tradițională olteană în inima capitalei. Vinuri de casă și mâncăruri autentice din Oltenia. Cramnicul lor de la butoi este o experiență unică.",
    category: "crama",
    lat: 44.4302,
    lng: 26.1042,
  },
  {
    name: "Grădina Lahovari",
    city: "București",
    judet: "Ilfov",
    address: "Piața Alexandru Lahovari 7, Sector 1",
    description: "Terasă urbană în mijlocul unei piațete liniștite din Floreasca. Cocktailuri artizanale, vin natural și atmosferă boho-chic. Locul preferat al Bucureștiului creativ.",
    category: "terasa",
    lat: 44.4523,
    lng: 26.0981,
  },
  // ── Cluj-Napoca ────────────────────────────────────────────────────────────
  {
    name: "Fabrica de Bere Ursus",
    city: "Cluj-Napoca",
    judet: "Cluj",
    address: "Str. Tăietura Turcului 52",
    description: "Fostă fabrică de bere transformată în complex cultural și gastronomic. Berărie artizanală proprie, spații de evenimente și restaurante în clădiri industriale reconvertite.",
    category: "berarie",
    lat: 46.7756,
    lng: 23.5718,
  },
  {
    name: "Joben Bistro",
    city: "Cluj-Napoca",
    judet: "Cluj",
    address: "Str. Mihail Kogălniceanu 20",
    description: "Bistro cu steampunk aesthetic și cea mai bună selecție de bere craft din Cluj. Bere la robinet din berării locale și internaționale, mâncare de pub de calitate.",
    category: "berarie",
    lat: 46.7680,
    lng: 23.5887,
  },
  {
    name: "Sikaru Taproom",
    city: "Cluj-Napoca",
    judet: "Cluj",
    address: "Str. Republicii 109",
    description: "Microberărie clujeană specializată în stiluri belgiene și englezești. Tripel-ul și Dubbel-ul lor sunt referințe în scena craft din Transilvania.",
    category: "berarie",
    lat: 46.7712,
    lng: 23.6003,
  },
  {
    name: "Terasa Festival",
    city: "Cluj-Napoca",
    judet: "Cluj",
    address: "Piața Unirii 15",
    description: "Terasă în aer liber în centrul Clujului cu vedere spre Catedrala Sf. Mihail. Beri locale, cocktailuri și atmosferă efervescentă în sezonul cald.",
    category: "terasa",
    lat: 46.7693,
    lng: 23.5896,
  },
  {
    name: "Lolita Bar",
    city: "Cluj-Napoca",
    judet: "Cluj",
    address: "Str. Memorandumului 14",
    description: "Bar de cocktailuri cu atmosferă vintage în inima Clujului. Barmanul face magie cu băuturi locale — palincă ardeleană în cocktailuri sofisticate.",
    category: "bar",
    lat: 46.7698,
    lng: 23.5843,
  },
  // ── Timișoara ──────────────────────────────────────────────────────────────
  {
    name: "Manufactura Craft Beer",
    city: "Timișoara",
    judet: "Timiș",
    address: "Str. Proclamației de la Timișoara 5",
    description: "Microberărie timișoreană cu producție proprie. Sortimente sezoniere și colaborări cu berari din toată Europa. Tap-room cu 20 de bere la robinet.",
    category: "berarie",
    lat: 45.7489,
    lng: 21.2083,
  },
  {
    name: "Berăria 700",
    city: "Timișoara",
    judet: "Timiș",
    address: "Piața Victoriei 2",
    description: "Berărie emblematică din centrul Timișoarei, numită în onoarea celor 700 de ani de atestare a orașului. Bere Timișoreana la halbă și mici tradiționali.",
    category: "berarie",
    lat: 45.7538,
    lng: 21.2254,
  },
  {
    name: "Barul de Jos",
    city: "Timișoara",
    judet: "Timiș",
    address: "Str. Alba Iulia 2",
    description: "Bar de cartier cu atmosferă retro, bere la halbă și muzică live în fiecare vineri seara. Un clasic timișorean pentru localnici.",
    category: "bar",
    lat: 45.7549,
    lng: 21.2087,
  },
  {
    name: "Cramele Recaș Showroom",
    city: "Timișoara",
    judet: "Timiș",
    address: "Str. Mercy 7",
    description: "Showroom-ul cramei Recaș în Timișoara. Degustări ghidate din gama completă, inclusiv sortimentele premium Solo Quinta și Schwaben Wein.",
    category: "crama",
    lat: 45.7491,
    lng: 21.2197,
  },
  // ── Iași ───────────────────────────────────────────────────────────────────
  {
    name: "Crama Cotnari — Iași",
    city: "Iași",
    judet: "Iași",
    address: "Bd. Ștefan cel Mare și Sfânt 16",
    description: "Prezentare oficială a cramei Cotnari în centrul Iașului. Degustări și vinuri direct de la producător, inclusiv rarul Grasă de Cotnari.",
    category: "crama",
    lat: 47.1585,
    lng: 27.6014,
  },
  {
    name: "Berăria Bolta Rece",
    city: "Iași",
    judet: "Iași",
    address: "Str. Rece 10",
    description: "Berărie subterană în pivnițe istorice din centrul Iașului. Atmosferă medievală, bere la butoi și muzică folk în weekenduri.",
    category: "berarie",
    lat: 47.1601,
    lng: 27.5873,
  },
  {
    name: "Irish Pub Galway",
    city: "Iași",
    judet: "Iași",
    address: "Str. Vasile Alecsandri 8",
    description: "Pub irlandez autentic cu whiskey-uri de colecție și meciuri live pe ecrane mari. Guinness la robinet și atmosferă de pub londonez.",
    category: "bar",
    lat: 47.1553,
    lng: 27.5982,
  },
  // ── Brașov ─────────────────────────────────────────────────────────────────
  {
    name: "Terasa Cetății",
    city: "Brașov",
    judet: "Brașov",
    address: "Str. Gheorghe Barițiu 1",
    description: "Terasă cu vedere panoramică spre Cetatea Brașovului. Bere Ciuc artizanală și specialități din zona Bârsei. Apus de soare superb.",
    category: "terasa",
    lat: 45.6427,
    lng: 25.5887,
  },
  {
    name: "Curtea Brașovului",
    city: "Brașov",
    judet: "Brașov",
    address: "Str. Apollonia Hirscher 2",
    description: "Bar și restaurant în centrul vechi, cu curte interioară medievală. Sortimente de bere transilvăneană și vin de Dealurile Brașovului.",
    category: "bar",
    lat: 45.6423,
    lng: 25.5875,
  },
  {
    name: "Club Diesel",
    city: "Brașov",
    judet: "Brașov",
    address: "Str. Mureșenilor 14",
    description: "Club și bar în centrul vechi al Brașovului. Cocktailuri creative și muzică electronică până dimineața. Terasa de vară este super aglomerată.",
    category: "club",
    lat: 45.6411,
    lng: 25.5877,
  },
  // ── Sibiu ──────────────────────────────────────────────────────────────────
  {
    name: "Festival 39",
    city: "Sibiu",
    judet: "Sibiu",
    address: "Piața Mare 10",
    description: "Bar cu terasa în Piața Mare din Sibiu. Locul de întâlnire al turiștilor și localnicilor, cu bere Habitus craft și vin de Târnave.",
    category: "terasa",
    lat: 45.7983,
    lng: 24.1510,
  },
  {
    name: "Berăria Neptun Sibiu",
    city: "Sibiu",
    judet: "Sibiu",
    address: "Str. Cetății 3",
    description: "Berărie tradițională sibieană cu pivniță istorică. Bere Neptun la halbă și meniuri de sezon cu ingrediente din Mărginimea Sibiului.",
    category: "berarie",
    lat: 45.7994,
    lng: 24.1488,
  },
  {
    name: "Crama Domeniilor Sighi",
    city: "Sighișoara",
    judet: "Mureș",
    address: "Str. Școala 9, Cetate",
    description: "Cramă în inima Cetății Sighișoarei, monument UNESCO. Vinuri de Târnave și degustări cu vedere spre turnul cu ceas.",
    category: "crama",
    lat: 46.2197,
    lng: 24.7954,
  },
  // ── Constanța ──────────────────────────────────────────────────────────────
  {
    name: "Club Doors Constanța",
    city: "Constanța",
    judet: "Constanța",
    address: "Bd. Mamaia 255",
    description: "Club pe malul Mării Negre cu terasa deschisă vara. Cocktailuri cu gin de mare și bere artizanală. Vederi spectaculoase spre Cazinoul din Constanța.",
    category: "club",
    lat: 44.1733,
    lng: 28.6575,
  },
  {
    name: "Berăria Cazino",
    city: "Constanța",
    judet: "Constanța",
    address: "Str. Remus Opreanu 5",
    description: "Berărie cu terasa lângă celebrul Cazinou din Constanța. Bere la halbă, fructe de mare și apus peste Marea Neagră.",
    category: "berarie",
    lat: 44.1748,
    lng: 28.6558,
  },
  // ── Sinaia ─────────────────────────────────────────────────────────────────
  {
    name: "Berăria Cantacuzino",
    city: "Sinaia",
    judet: "Prahova",
    address: "Str. Octavian Goga 2",
    description: "Berărie artizanală la poalele Castelului Cantacuzino. Bere produsă cu apă de munte din Bucegi, atmosferă montană autentică și priveliști spre pârtii.",
    category: "berarie",
    lat: 45.3534,
    lng: 25.5458,
  },
  // ── Oradea ─────────────────────────────────────────────────────────────────
  {
    name: "La Cazinou Bar",
    city: "Oradea",
    judet: "Bihor",
    address: "Piața Unirii 22",
    description: "Bar în clădire Art Nouveau restaurată în centrul Oradiei. Cocktailuri clasice, selecție de whiskey-uri și terasa cu vedere spre Criș.",
    category: "bar",
    lat: 47.0465,
    lng: 21.9189,
  },
  // ── Vălenii de Munte ───────────────────────────────────────────────────────
  {
    name: "Zăganu Taproom",
    city: "Vălenii de Munte",
    judet: "Prahova",
    address: "Str. Industriilor 4",
    description: "Taproom-ul berăriei artizanale Zăganu, una dintre cele mai apreciate din România. Bere proaspătă direct din tanc, tur al fabricii și shop cu sortimente limitate.",
    category: "berarie",
    lat: 45.1847,
    lng: 26.0428,
  },
];
